// Deprecated: Resume state is now managed by normalized Redux slice. This hook is kept
// for backward compatibility but returns no-ops to avoid runtime errors during transition.
export function useResumeStore(_resumeId: string) {
  return {
    resumeData: { id: null, name: '', template_id: null, theme: { id: 'minimal', font: 'inter' }, personal_info: {}, sections: [], summary: '' },
    saving: false,
    hasUnsavedChanges: false,
    exporting: false,
    setExporting: () => {},
    importing: false,
    setImporting: () => {},
    skillsTags: [],
    availableSections: [],
    jdHints: [],
    setName: () => {},
    setTemplateId: () => {},
    setFontId: () => {},
    setThemeId: () => {},
    handleSave: () => {},
    updatePersonalInfo: () => {},
    setSkillsFromTags: () => {},
    setSummaryText: () => {},
    enhanceSummary: async (s: string) => Promise.resolve(s),
    exportPdf: () => {},
    exportDocx: () => {},
    importPdf: () => {},
    addProjectItem: () => {},
    removeProjectItem: () => {},
    setProjectField: () => {},
    addProjectHighlight: () => {},
    removeProjectHighlight: () => {},
    setProjectHighlight: () => {},
    enhanceExperienceBullet: async (_i: number, _bi: number, s: string) => Promise.resolve(s),
    suggestBullets: () => {},
    addSection: () => {},
    addExperienceItem: () => {},
    removeExperienceItem: () => {},
    setExperienceField: () => {},
    addExperienceBullet: () => {},
    removeExperienceBullet: () => {},
    setExperienceBullet: () => {},
    replaceExperienceBullets: () => {},
    addEducationItem: () => {},
    removeEducationItem: () => {},
    setEducationField: () => {},
    addAchievementItem: () => {},
    removeAchievementItem: () => {},
    setAchievementField: () => {},
    addCertificationItem: () => {},
    removeCertificationItem: () => {},
    setCertificationField: () => {},
    ensureSeed: () => {},
  }
}

export default useResumeStore


